name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
    - uses: android-actions/setup-android@v2
    - run: ./gradlew assembleDebug
    - uses: actions/upload-artifact@v3
      with:
        name: GeoVision-Pro.apk
        path: app/build/outputs/apk/debug/app-debug.apk
