name: Android CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.3

      - name: Set up JDK 11
uses: actions/upload-artifact@v3.1.3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK Artifact
uses: actions/upload-artifact@v3.1.3
        with:
          name: GeoApp-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk
