name: Android CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: List APK files (for verification)
        run: ls -R app/build/outputs/apk/

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GeoApp-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk
